name: "Cache base caputre"

on:
  workflow_call:
    inputs:
      git-commit-hash:
        required: true
        type: string

jobs:
  cache-base-caputre:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-commit-hash }}
      - uses: actions/cache@v4
        id: capture-cache
        with:
          path: nextjs-sandbox/.reg/expected
          key: vrt-captures-${{ inputs.git-commit-hash }}

      - name: Setup Node.js
        if: steps.capture-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: ./nextjs-sandbox

      # TODO chromiumのキャッシュをどうするか
      # puppeteerのバージョンをキーとしてchromium本体のバイナリをキャッシュする？
      # 依存関係のキャッシュをどうする？
      - name: Install dependencies and prepare cache
        working-directory: ./nextjs-sandbox
        if: steps.capture-cache.outputs.cache-hit != 'true'
        run: |
          npm ci

          npm run install:chrome
          npm run server-storycap
          mkdir .reg
          mv __screenshots__ .reg/expected
