name: VRT-検証元となる画像の作成

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cache-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      # ダミーキャッシュファイルの作成
      - name: Create dummy cache file
        run: |
          mkdir -p nextjs-sandbox/.reg
          echo "testtext-changed" > nextjs-sandbox/.reg/test.txt

      # test.txt のキャッシュ
      - name: Cache test.txt
        uses: actions/cache@v4
        with:
          path: nextjs-sandbox/.reg/test.txt
          key: vrt-expected-captures

      # test.txt がキャッシュされているか確認
      - name: Check if test.txt is cached
        run: cat nextjs-sandbox/.reg/test.txt
