name: VRT-テスト実行

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  display-cache:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      # キャッシュの復元
      - name: Cache test.txt
        uses: actions/cache@v4
        with:
          path: nextjs-sandbox/.reg/test.txt
          key: vrt-expected-captures

      # キャッシュされた test.txt を表示
      - name: Display cached test.txt
        run: |
          if [ -f nextjs-sandbox/.reg/test.txt ]; then
            cat nextjs-sandbox/.reg/test.txt
          else
            echo "Cache file does not exist."
          fi
