name: VRT-検証元となる画像の作成

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cache-expected-captures:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      - name: Set up chromium
        run: |
          mkdir -p nextjs-sandbox/.reg
          echo "testtext-changed-2" > nextjs-sandbox/.reg/test.txt
          apt-get update
          apt-get install -y 
          libx11-xcb1
          libxcomposite1
          libxcursor1
          libxdamage1
          libxi6
          libxtst6
          libcups2
          libxss1
          libxrandr2
          libasound2
          libpango-1.0-0
          libatk1.0-0
          libatk-bridge2.0-0
          libgtk-3-0

      # test.txt のキャッシュ
      - name: Cache test.txt
        uses: actions/cache/save@v4
        with:
          path: nextjs-sandbox/.reg/
          key: vrt-captures-${{ github.sha }}

      # test.txt がキャッシュされているか確認
      - name: Check if test.txt is cached
        run: cat nextjs-sandbox/.reg/test.txt
