name: VRT-検証元となる画像の作成

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cache-expected-captures:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: node:20
    uses: ./.github/workflows/cache-base-caputre.yml
    with:
      git-commit-hash: ${{ github.sha }}
