name: VRT-検証元となる画像の作成

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cache-expected-captures:
    uses: ./.github/workflows/cache-base-caputre.yml
    with:
      git-commit-hash: ${{ github.sha }}
