name: VRT-テスト実行

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  cache-expected-captures:
    uses: ./.github/workflows/cache-base-caputre.yml
    with:
      git-commit-hash: ${{ github.event.pull_request.base.sha }}

  display-cache:
    runs-on: ubuntu-latest
    container:
      image: node:20
    needs: [cache-expected-captures]
    steps:
      - uses: actions/checkout@v4

      - name: Cache test.txt
        uses: actions/cache/restore@v4
        with:
          path: nextjs-sandbox/.reg/expected
          key: vrt-captures-${{ github.event.pull_request.base.sha }}

      - name: Display cache
        run: ls -a nextjs-sandbox/.reg
