name: VRT-検証元となる画像の作成

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  cache-readme:
    runs-on: ubuntu-latest # この行はコンテナを使用するために必要、ジョブ自体は指定したコンテナ内で実行される
    timeout-minutes: 10
    container:
      image: node:20 # Node.js のバージョン 20 を使用

    steps:
      - uses: actions/checkout@v4

      - name: Cache README.md
        uses: actions/cache@v4
        with:
          path: |
            README.md
          key: vrt-expected-captures

      - name: Check if README.md is cached
        run: cat "README.md"
